# Generated by Django 2.0.3 on 2018-03-30 07:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID sur demarches-simplifiees.fr')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('initiated', 'En construction'), ('received', 'En instruction'), ('closed', 'Accepte'), ('refused', 'Refusé'), ('without_continuation', 'Sans suite')], db_index=True, max_length=50, verbose_name='Statut')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification')),
                ('department', models.CharField(db_index=True, max_length=255, verbose_name='Département qui figure sur le titre de séjour')),
                ('raw_json', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Résultat JSON brut')),
            ],
        ),
    ]
