version: '3'

services:

  db:
    env_file:
      - .env
    image: postgres:9.6-alpine
    container_name: wif_postgres
    volumes:
      - wif_pgdata:/var/lib/postgresql
      - ./docker/common/psql_init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    restart: always
    ports:
      - "5433:5432"

  web:
    env_file:
      - .env
    depends_on:
      - db
    container_name: wif_django
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"

volumes:
  wif_pgdata:
