#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_WIF_DATABASE_USER WITH ENCRYPTED PASSWORD '$POSTGRES_WIF_DATABASE_PASSWORD';
  CREATE DATABASE $POSTGRES_WIF_DATABASE_NAME OWNER $POSTGRES_WIF_DATABASE_USER;
  ALTER USER $POSTGRES_WIF_DATABASE_USER CREATEDB;
EOSQL
