#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $WIF_DATABASE_USER WITH ENCRYPTED PASSWORD '$WIF_DATABASE_PASSWORD';
  CREATE DATABASE $WIF_DATABASE_NAME OWNER $WIF_DATABASE_USER;
  ALTER USER $WIF_DATABASE_USER CREATEDB;
EOSQL
