# Generated by Django 2.0.4 on 2018-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='department',
            field=models.CharField(db_index=True, help_text='Département qui figure sur le titre de séjour', max_length=255, verbose_name='Département titre de séjour'),
        ),
    ]
